package ui;

import dao.CourseDao;
import models.Course;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class CoursePanel extends JPanel {

    private JTextField courseNameField, creditsField, deptIdField;
    private JButton addBtn, updateButton, deleteButton, clearButton;
    private JTable table;
    private DefaultTableModel tableModel;
    private CourseDao dao = new CourseDao();

    public CoursePanel() {
        setLayout(new BorderLayout(10, 10));

        // --- FORM PANEL ---
        JPanel formPanel = new JPanel(new GridLayout(4, 2, 10, 10));
        formPanel.setBorder(BorderFactory.createTitledBorder("Course Details"));

        // REMOVED course_idField — ID is auto generated by database
        // course name is now purely a String — no parseInt anywhere near it
        formPanel.add(new JLabel("Course Name:"));
        courseNameField = new JTextField();
        formPanel.add(courseNameField);

        formPanel.add(new JLabel("Credits:"));
        creditsField = new JTextField();
        formPanel.add(creditsField);

        formPanel.add(new JLabel("Department ID:"));
        deptIdField = new JTextField();
        formPanel.add(deptIdField);

        add(formPanel, BorderLayout.NORTH);

        // --- TABLE ---
        tableModel = new DefaultTableModel(
                new String[]{"Course ID", "Course Name", "Credits", "Department ID"}, 0);
        table = new JTable(tableModel);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        add(new JScrollPane(table), BorderLayout.CENTER);

        // --- BUTTONS ---
        JPanel btnPanel = new JPanel(new FlowLayout());
        addBtn       = new JButton("Add");
        updateButton = new JButton("Update");
        deleteButton = new JButton("Delete");
        clearButton  = new JButton("Clear");

        btnPanel.add(addBtn);
        btnPanel.add(updateButton);
        btnPanel.add(deleteButton);
        btnPanel.add(clearButton);
        add(btnPanel, BorderLayout.SOUTH);

        // --- BUTTON ACTIONS ---
        addBtn.addActionListener(e -> addCourse());
        updateButton.addActionListener(e -> updateCourse());
        deleteButton.addActionListener(e -> deleteCourse());
        clearButton.addActionListener(e -> clearFields());

        // --- CLICK ROW TO FILL FORM ---
        // column 0 = Course ID (int)
        // column 1 = Course Name (String)  ← was broken before
        // column 2 = Credits (int)
        // column 3 = Department ID (int)
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                int row = table.getSelectedRow();
                if (row != -1) {
                    courseNameField.setText(tableModel.getValueAt(row, 1).toString());
                    creditsField.setText(tableModel.getValueAt(row, 2).toString());
                    deptIdField.setText(tableModel.getValueAt(row, 3).toString());
                }
            }
        });

        loadData();
    }

    private void loadData() {
        tableModel.setRowCount(0);
        try {
            List<Course> list = dao.getAllCourses();
            for (Course c : list) {
                tableModel.addRow(new Object[]{
                        c.getCourseId(),
                        c.getCourseName(),   // this is a String — no parsing needed
                        c.getCredits(),
                        c.getDeptId()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    private void addCourse() {
        // courseName is read as plain String — no parseInt
        String courseName = courseNameField.getText().trim();
        String credit     = creditsField.getText().trim();
        String deptId     = deptIdField.getText().trim();

        // Validate fields are not empty
        if (courseName.isEmpty() || credit.isEmpty() || deptId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        // Validate credits and deptId are actually numbers
        try {
            Integer.parseInt(credit);
            Integer.parseInt(deptId);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Credits and Department ID must be numbers");
            return;
        }

        // Now add — courseName stays as String, only credits and deptId are parsed
        try {
            dao.addCourse(new Course(
                    courseName,                  // String — no parseInt
                    Integer.parseInt(credit),    // int
                    Integer.parseInt(deptId)     // int
            ));
            JOptionPane.showMessageDialog(this, "Course added successfully");
            clearFields();
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void updateCourse() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        // Get ID from selected table row
        int id            = (int) tableModel.getValueAt(row, 0);
        String courseName = courseNameField.getText().trim();
        String credit     = creditsField.getText().trim();
        String deptId     = deptIdField.getText().trim();

        if (courseName.isEmpty() || credit.isEmpty() || deptId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields");
            return;
        }

        try {
            dao.updateCourse(new Course(
                    id,                          // int - from selected row
                    courseName,                  // String — no parseInt
                    Integer.parseInt(credit),    // int
                    Integer.parseInt(deptId)     // int
            ));
            JOptionPane.showMessageDialog(this, "Course updated successfully");
            clearFields();
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void deleteCourse() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        int courseId = (int) tableModel.getValueAt(row, 0);
        int confirm  = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?");
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                dao.deleteCourse(courseId);
                JOptionPane.showMessageDialog(this, "Course deleted successfully");
                clearFields();
                loadData();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }

    private void clearFields() {
        courseNameField.setText("");
        creditsField.setText("");
        deptIdField.setText("");
        table.clearSelection();
    }
}